---
name: 'Publish Ansible Collection'
description: 'Build and publish an Ansible Collection to Ansible Galaxy'
author: 'Simon Baerlocher <s.baerlocher@sbaerlocher.ch>"'
inputs:
  api_key:
    description: |
      Ansible Galaxy API key. This should be stored in a Secret on Github.

      See https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables.
    required: true
  galaxy_config_file:
    description: 'A collection must have a galaxy.yml file that contains the necessary information to build a collection artifact. Defaults to "galaxy.yml" in the project root.'
    default: 'galaxy.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'black'
