name: Testing Action

on: [pull_request]

jobs:
  test_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Report Ansible version
        run: ansible --version

      - name: Testing action
        uses: ./
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          collection_dir: tests/collection
