name: Testing the Action

on: [pull_request]

jobs:
  test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Report Ansible version
        run: ansible --version

      - name: Testing the action
        uses: ./../
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
